#!/usr/bin/env python
import rospy
from ropod_sound_communication.sound_communication import SoundCommunicator

if __name__ == '__main__':
    rospy.init_node('ropod_sound_communication')
    sound_communicator = SoundCommunicator()
    rospy.spin()
